### ISSUE TITLE
버그 수정

### ISSUE THREAD

**Issue by Malloc72P** [Malloc72P/QnaOverflow#17]

**Comment by kyupid** [comment]
![Screenshot_20220124-185849_Samsung Internet.jpg](https://user-images.githubusercontent.com/59721293/150761541-ad126494-6375-4715-80bb-8ca7a25bdc7e.jpg)

게시물등록 버그제보하려했습니다 ㅎㅎ500에러

**Comment by kyupid** [comment]
![Screenshot_20220124-190228_Samsung Internet.jpg](https://user-images.githubusercontent.com/59721293/150762106-2bd02cfe-39b0-4efb-902b-9b3f074bb4a6.jpg)
업->다운->업 안돼요

**Comment by Malloc72P** [comment]
> ![Screenshot_20220124-190228_Samsung Internet.jpg](https://user-images.githubusercontent.com/59721293/150762106-2bd02cfe-39b0-4efb-902b-9b3f074bb4a6.jpg) 업->다운->업 안돼요

헉 아깐 잘 됐는데 뭔가 문제가 있나봐요 ㅠㅠ 
알려줘서 고마워요! 😍

**Comment by kyupid** [comment]
배포했을때 버그찾는게 꿀잼이죠 ㅋㅋㅋ
