### ISSUE TITLE
화면구현 & 기능구현

### ISSUE THREAD

**Issue by Malloc72P** [Malloc72P/QnaOverflow#3]
### 화면 구현 & 기능 구현
- [x] #5
  - [x] 페이지 레이아웃 구현
  - [x] 네비바 구현
  - [x] 사이드바 구현
  - [x] 목록조회 구현
  - [x] 태그조회기능 구현
  - [x] OSIV 기능 끄기(서비스에서 필요한 데이터 다 퍼올 수 있도록 구현하기
  - [x] 쿼리 최적화
- [x] #4
  - [x] 질문글 상세보기 페이지 작업
  - [x] 푸터 구현
  - [x] 댓글 목록조회(depth 없는 버전)
  - [x] 댓글 작성 폼
  - [x] 답변글 작성 폼
  - [x] 페이지를 프래그먼트로 잘게 분리하기
  - [x] 질문글 상세조회 서비스 구현 및 뷰와 연동하기
  - [x] 대댓글 목록조회 구현(depth 있는 버전)
- [x] #6
  - [x] 작성
  - [x] 삭제
  - [x] 수정
- [x] #7
  - [x] 작성
  - [x] 삭제
  - [x] 수정
- [x] #8
  - [x] 작성
  - [x] 삭제
  - [x] 수정
- [x] #9
  - [x] 태그 목록조회 페이지
  - [x] 태그 생성 페이지 
  - [x] 태그 수정 페이지 
  - [x] 태그 삭제
  - [x] 태그검색 API
- [x] #14
  - [x] 태그 삭제하면 질문게시글에 적용된 태그도 지워주기
  - [x] 질문게시글 생성할 때 태그 추가하는 기능 넣기
  - [x] 질문게시글 수정할 때 태그 수정하는 기능 넣기
- [x] #10
  - [x] upvoteCount & downvoteCount 제거
  - [x] Vote 엔티티 추가(투표자, 게시글, 투표유형)
  - [x] 투표기능 구현(Vote 생성기능)
  - [x] 반대로 투표하면, 기존 투표 없애고 새로운 투표를 생성하도록 구현
  - [x] 중복투표시 예외 발생
  - [x] VoteService를 통해 여러 게시글의 투표점수 집계기능 구현
  - [x] 투표점수 조회기능 뷰와 연동
  - [x] 투표하기 기능 뷰와 연동
  - [x] 조회수 기능
- [x] #11
  - [x] 제목으로 검색하기
  - [x] 작성자로 검색하기
  - [x] 답변개수로 검색하기(answers : 1)을 하면 답변 존재하는지 검사하는게 됨
  - [x] 태그로 검색하기
  - [x] 투표점수로 검색하기
  - [x] 페이징 처리 구현
  - [x] 뷰에서 페이지 객체를 받아서 랜더링하기
  - [x] 페이지네이션 구현
  - [x] 질문글 목록조회도 search로 질문글을 불러오도록 수정
  - [x] 날짜순 정렬 추가
- [x] #12
  - [x] 구글 로그인 기능 구현
  - [x] 로그아웃, 회원탈퇴 기능 구현
  - [x] 네이버 로그인 기능 구현
  - [x] 질문글 작성하기와 연동
  - [x] 질문글 수정, 삭제하기와 연동
  - [x] 답변글 수정, 삭제하기와 연동
  - [x] 대댓글 작성하기와 연동
  - [x] 대댓글 수정, 삭제하기와 연동
  - [x] 질문 & 답변글 up, downvote 기능과 연동
- [x] #15
  - [x] 좀 더 나은 테스트 코드로 고쳐보기
  - [x] 컨트롤러 테스트
- [x] #13
  - [x] 404, 500등에 대한 에러페이지 구현
  - [x] API 예외에 대한 처리 구현(서버에서 내려준 에러메세지를 출력할 수 있도록)
- [x] #16
  - [x] 젠킨스 서버에 oauth 프로퍼티 파일을 따로 업로드하기
  - [x] 배포환경의 oauth redirect uri이 달라서 발생하는 문제 해결하기
  - [x] https 적용
- [x] #17
  - [x] API 주소 잘못 등록된 문제 해결하기
  - [x] 답변수 집계할 때 제거된 답변도 포함되는 문제 해결하기
  - [x] 질문하기 기능에서 500에러 발생함 + 투표기능도.
         -> 기본 에러메세지 파일이 없어서 발생하는 것으로 추정됨
  - [x] 깜빡한것 구현하기(검색창 도움말)
  - [x] pointerdown으로 이벤트 리스너 등록한거 전부 바꾸기
  - [x] 깜빡한것 구현하기(푸터 링크 안되는거!)
  - [x] 삭제된 댓글을 수정할 수 있는 문제
  - [x] 모바일 환경에서 대댓글 들여쓰기가 잘 안보임(너무 적게 밀어놨음)
- [x] 기능개선
  - [x] 질문목록조회 페이지에서 질문이 총 몇개인지도 보여주기
  - [x] 멤버, 태그 목록조회 페이지에도 페이징 처리 추가하기
  - [x] 기본 에러페이지 고장남. 404 페이지 안나옴
  - [x] 태그랑 제목에 공백이 들어있으면 검색 안됨
  - [x] 태그 검색기능에서 너무 많은 태그가 노출되는 문제 해결하기
  - [x] 더미데이터를 생성하는 스크립트때문에 중복된 이름의 태그가 등록되는 문제 해결하기
  - [x] 회원 및 태그 목록조회에서 생성일 기준으로 내림차순 정렬하도록 개선하기
  - [x] 태그수정하기 500에러 발생

**Comment by kyupid** [comment]
안녕하세요 나스 데모 서버는 언제 열려요? ㅎㅎ 궁금합니다

**Comment by Malloc72P** [comment]
> 안녕하세요 나스 데모 서버는 언제 열려요? ㅎㅎ 궁금합니다

커밍쑨입니다 ㅎㅎ

**Comment by kyupid** [comment]
100개 가량의 태스크를 모두 해내셨네요..대단하십니당 고생많으셨어요 💪👏👏

**Comment by Malloc72P** [comment]
> 100개 가량의 태스크를 모두 해내셨네요..대단하십니당 고생많으셨어요 💪👏👏

고마워요 큐 ㅎㅎ(❁´◡`❁)
